name: Build

on:
  push:
    branches-ignore:
      - 'wip*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 14.20.0
          cache: 'npm'

      - name: Install dependencies
        run:  npm clean-install --include=dev

      - name: Dump title IDs from Tinfoil DB
        run:  npm run tinfoil

      - name: Dump eShop data
        run:  npm run eshop

      - name: Build
        run:  npm run build

      # If the action trigger was NOT a version tag
      - name: Upload artifact
        if:   startsWith(github.ref, 'refs/tags/v') == false
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: out/**/*

      # If the action trigger was a version tag
      - name: Make distributables
        if:   startsWith(github.ref, 'refs/tags/v')
        run:  npm run make

      - name: Publish to Releases
        if:   startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/make/**/*
